version: 2
updates:
  - package-ecosystem: "pip"
    target-branch: "dev"
    directory: "/"
    labels:
      - "dependency"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    target-branch: "dev"
    directory: "/"
    labels:
      - "dependency"
      - "docker"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    target-branch: "dev"
    directory: "/"
    labels:
      - "dependency"
      - "docker"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    target-branch: "dev"
    directory: "/"
    labels:
      - "cicd"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"

  - package-ecosystem: "pre-commit"
    target-branch: "dev"
    directory: "/"
    labels:
      - "styles"
      - "pre-commit"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
