services:
  api:
    ports: !override
      - "8080:8080"
    environment:
      DEBUG: "true"
      PYTHONUNBUFFERED: 1
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
    deploy:
      replicas: 1
