"""Tests for organization one-time invite links.

A link is generated by an admin and shared. The first user to accept it burns it:
every later acceptance attempt returns 410.
"""

from datetime import datetime, timedelta, timezone
from unittest.mock import AsyncMock, MagicMock

import pytest
from fastapi import HTTPException

from core.config import settings
from tests.test_organization_service import _make_org_service


def _make_member_service(org_svc):
    from services.organization_member_service import OrganizationMemberService

    svc = OrganizationMemberService.__new__(OrganizationMemberService)
    svc.db = org_svc.db
    svc.history = MagicMock()
    svc.history.get_user = AsyncMock(return_value={"_id": "u2", "first_name": "Bob"})
    svc.orgs = org_svc
    svc.members_collection = settings.ORGANIZATION_MEMBERS_COLLECTION
    svc.invites_collection = settings.ORGANIZATION_INVITES_COLLECTION
    svc.invite_prefix = "oinv-"
    svc.member_prefix = "omem-"
    return svc


async def test_admin_creates_invite_with_join_path():
    org_svc = _make_org_service()
    org = await org_svc.create_organization(user_id="u1", name="Legal Dept")
    svc = _make_member_service(org_svc)

    invite = await svc.create_invite(org["_id"], "u1")

    assert invite["_id"].startswith("oinv-")
    assert invite["org_id"] == org["_id"]
    assert invite["created_by"] == "u1"
    assert invite["status"] == "pending"
    assert invite["accepted_by"] is None
    assert invite["join_path"] == f"organizations/join/{invite['_id']}"
    assert invite["expires_at"] > datetime.now(timezone.utc)


async def test_non_admin_cannot_create_invite():
    org_svc = _make_org_service()
    org = await org_svc.create_organization(user_id="u1", name="Legal Dept")
    org_svc.db.docs[settings.ORGANIZATION_MEMBERS_COLLECTION].append(
        {
            "_id": "omem-2",
            "org_id": org["_id"],
            "user_id": "u2",
            "role": "member",
            "status": "active",
            "joined_at": datetime.now(timezone.utc),
        }
    )
    svc = _make_member_service(org_svc)

    with pytest.raises(HTTPException) as exc:
        await svc.create_invite(org["_id"], "u2")
    assert exc.value.status_code == 403


async def test_create_invite_rejected_when_org_is_full():
    org_svc = _make_org_service()
    org = await org_svc.create_organization(user_id="u1", name="Legal Dept")
    for i in range(settings.ORG_SEAT_LIMIT - 1):
        org_svc.db.docs[settings.ORGANIZATION_MEMBERS_COLLECTION].append(
            {
                "_id": f"omem-{i}",
                "org_id": org["_id"],
                "user_id": f"filler{i}",
                "role": "member",
                "status": "active",
                "joined_at": datetime.now(timezone.utc),
            }
        )
    svc = _make_member_service(org_svc)

    with pytest.raises(HTTPException) as exc:
        await svc.create_invite(org["_id"], "u1")
    assert exc.value.status_code == 409


async def test_list_pending_invites_hides_expired():
    org_svc = _make_org_service()
    org = await org_svc.create_organization(user_id="u1", name="Legal Dept")
    svc = _make_member_service(org_svc)
    fresh = await svc.create_invite(org["_id"], "u1")
    stale = await svc.create_invite(org["_id"], "u1")
    stale["expires_at"] = datetime.now(timezone.utc) - timedelta(hours=1)

    out = await svc.list_pending_invites(org["_id"], "u1")

    assert [i["_id"] for i in out] == [fresh["_id"]]


async def test_revoke_invite_marks_it_revoked():
    org_svc = _make_org_service()
    org = await org_svc.create_organization(user_id="u1", name="Legal Dept")
    svc = _make_member_service(org_svc)
    invite = await svc.create_invite(org["_id"], "u1")

    await svc.revoke_invite(org["_id"], invite["_id"], "u1")

    stored = svc.db.docs[settings.ORGANIZATION_INVITES_COLLECTION][0]
    assert stored["status"] == "revoked"


async def test_accept_invite_creates_member_and_burns_the_link():
    org_svc = _make_org_service()
    org = await org_svc.create_organization(user_id="u1", name="Legal Dept")
    svc = _make_member_service(org_svc)
    invite = await svc.create_invite(org["_id"], "u1")

    result = await svc.accept_invite(invite["_id"], "u2")

    assert result["org_id"] == org["_id"]
    assert result["user_id"] == "u2"
    assert result["membership_role"] == "member"

    stored_invite = svc.db.docs[settings.ORGANIZATION_INVITES_COLLECTION][0]
    assert stored_invite["status"] == "accepted"
    assert stored_invite["accepted_by"] == "u2"
    assert stored_invite["accepted_at"] is not None

    members = svc.db.docs[settings.ORGANIZATION_MEMBERS_COLLECTION]
    assert [m["user_id"] for m in members] == ["u1", "u2"]
    assert members[1]["role"] == "member"
    assert members[1]["status"] == "active"
    assert "invited_by" not in members[1]


async def test_second_user_cannot_reuse_the_same_link():
    org_svc = _make_org_service()
    org = await org_svc.create_organization(user_id="u1", name="Legal Dept")
    svc = _make_member_service(org_svc)
    invite = await svc.create_invite(org["_id"], "u1")
    await svc.accept_invite(invite["_id"], "u2")

    with pytest.raises(HTTPException) as exc:
        await svc.accept_invite(invite["_id"], "u3")
    assert exc.value.status_code == 410


async def test_losing_the_claim_race_returns_410_and_creates_no_membership():
    """The conditional invite claim IS the single-use gate.

    If the claim update matches no pending row — another request won the race — the
    accept must abort before any membership row is written. Simulated by forcing
    update_documents to report zero modified rows.
    """
    org_svc = _make_org_service()
    org = await org_svc.create_organization(user_id="u1", name="Legal Dept")
    svc = _make_member_service(org_svc)
    invite = await svc.create_invite(org["_id"], "u1")
    svc.db.update_documents = AsyncMock(return_value=0)

    with pytest.raises(HTTPException) as exc:
        await svc.accept_invite(invite["_id"], "u2")
    assert exc.value.status_code == 410

    members = svc.db.docs[settings.ORGANIZATION_MEMBERS_COLLECTION]
    assert [m["user_id"] for m in members] == ["u1"]


async def test_removed_member_rejoining_reactivates_their_row():
    """(org_id, user_id) is uniquely indexed, so a removed member still owns that key.

    Re-joining must reactivate the existing row, not insert a second one — a blind
    insert would raise DuplicateKeyError against the real index.
    """
    org_svc = _make_org_service()
    org = await org_svc.create_organization(user_id="u1", name="Legal Dept")
    svc = _make_member_service(org_svc)
    org_svc.db.docs[settings.ORGANIZATION_MEMBERS_COLLECTION].append(
        {
            "_id": "omem-old",
            "org_id": org["_id"],
            "user_id": "u2",
            "role": "member",
            "status": "removed",
            "joined_at": datetime.now(timezone.utc),
        }
    )
    invite = await svc.create_invite(org["_id"], "u1")

    result = await svc.accept_invite(invite["_id"], "u2")

    assert result["membership_role"] == "member"
    rows = [
        m
        for m in svc.db.docs[settings.ORGANIZATION_MEMBERS_COLLECTION]
        if m["user_id"] == "u2"
    ]
    assert len(rows) == 1
    assert rows[0]["_id"] == "omem-old"
    assert rows[0]["status"] == "active"


async def test_revoke_cannot_clobber_an_already_accepted_invite():
    org_svc = _make_org_service()
    org = await org_svc.create_organization(user_id="u1", name="Legal Dept")
    svc = _make_member_service(org_svc)
    invite = await svc.create_invite(org["_id"], "u1")
    await svc.accept_invite(invite["_id"], "u2")

    with pytest.raises(HTTPException) as exc:
        await svc.revoke_invite(org["_id"], invite["_id"], "u1")
    assert exc.value.status_code == 400

    stored = svc.db.docs[settings.ORGANIZATION_INVITES_COLLECTION][0]
    assert stored["status"] == "accepted"
    assert stored["accepted_by"] == "u2"


async def test_accept_expired_invite_returns_410():
    org_svc = _make_org_service()
    org = await org_svc.create_organization(user_id="u1", name="Legal Dept")
    svc = _make_member_service(org_svc)
    invite = await svc.create_invite(org["_id"], "u1")
    invite["expires_at"] = datetime.now(timezone.utc) - timedelta(hours=1)

    with pytest.raises(HTTPException) as exc:
        await svc.accept_invite(invite["_id"], "u2")
    assert exc.value.status_code == 410


async def test_accept_revoked_invite_returns_410():
    org_svc = _make_org_service()
    org = await org_svc.create_organization(user_id="u1", name="Legal Dept")
    svc = _make_member_service(org_svc)
    invite = await svc.create_invite(org["_id"], "u1")
    await svc.revoke_invite(org["_id"], invite["_id"], "u1")

    with pytest.raises(HTTPException) as exc:
        await svc.accept_invite(invite["_id"], "u2")
    assert exc.value.status_code == 410


async def test_accept_is_idempotent_for_an_existing_member():
    org_svc = _make_org_service()
    org = await org_svc.create_organization(user_id="u1", name="Legal Dept")
    svc = _make_member_service(org_svc)
    invite = await svc.create_invite(org["_id"], "u1")

    result = await svc.accept_invite(invite["_id"], "u1")

    assert result["membership_role"] == "admin"
    assert len(svc.db.docs[settings.ORGANIZATION_MEMBERS_COLLECTION]) == 1


async def test_accept_rejected_when_seat_limit_reached():
    org_svc = _make_org_service()
    org = await org_svc.create_organization(user_id="u1", name="Legal Dept")
    svc = _make_member_service(org_svc)
    invite = await svc.create_invite(org["_id"], "u1")
    # Fill the remaining seats AFTER the link was minted.
    for i in range(settings.ORG_SEAT_LIMIT - 1):
        org_svc.db.docs[settings.ORGANIZATION_MEMBERS_COLLECTION].append(
            {
                "_id": f"omem-{i}",
                "org_id": org["_id"],
                "user_id": f"filler{i}",
                "role": "member",
                "status": "active",
                "joined_at": datetime.now(timezone.utc),
            }
        )

    with pytest.raises(HTTPException) as exc:
        await svc.accept_invite(invite["_id"], "u2")
    assert exc.value.status_code == 409


async def test_invite_preview_exposes_org_name_without_membership():
    org_svc = _make_org_service()
    org = await org_svc.create_organization(user_id="u1", name="Legal Dept")
    svc = _make_member_service(org_svc)
    invite = await svc.create_invite(org["_id"], "u1")

    preview = await svc.get_invite_preview(invite["_id"], "u2")

    assert preview["org_name"] == "Legal Dept"
    assert preview["status"] == "pending"
    assert preview["already_member"] is False
    assert preview["seats_remaining"] == settings.ORG_SEAT_LIMIT - 1


async def test_list_members_returns_admin_first_with_profile_fields():
    org_svc = _make_org_service()
    org = await org_svc.create_organization(user_id="u1", name="Legal Dept")
    svc = _make_member_service(org_svc)
    profiles = {
        "u1": {"_id": "u1", "first_name": "Ada", "last_name": "L", "username": "ada"},
        "u2": {"_id": "u2", "first_name": "Bob", "last_name": "M", "username": "bob"},
    }
    svc.history.get_user = AsyncMock(side_effect=lambda uid: profiles.get(uid))
    invite = await svc.create_invite(org["_id"], "u1")
    await svc.accept_invite(invite["_id"], "u2")

    members = await svc.list_members(org["_id"], "u1")

    assert [m["user_id"] for m in members] == ["u1", "u2"]
    assert members[0]["role"] == "admin"
    assert members[0]["first_name"] == "Ada"
    assert members[1]["role"] == "member"
    assert members[1]["username"] == "bob"


async def test_list_members_rejects_non_member():
    org_svc = _make_org_service()
    org = await org_svc.create_organization(user_id="u1", name="Legal Dept")
    svc = _make_member_service(org_svc)

    with pytest.raises(HTTPException) as exc:
        await svc.list_members(org["_id"], "stranger")
    assert exc.value.status_code == 403


async def test_revoke_rejects_already_revoked_invite():
    org_svc = _make_org_service()
    org = await org_svc.create_organization(user_id="u1", name="Legal Dept")
    svc = _make_member_service(org_svc)
    invite = await svc.create_invite(org["_id"], "u1")
    await svc.revoke_invite(org["_id"], invite["_id"], "u1")

    with pytest.raises(HTTPException) as exc:
        await svc.revoke_invite(org["_id"], invite["_id"], "u1")
    assert exc.value.status_code == 400
